restructure /microservices & compose.yaml

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -7,9 +7,16 @@ WORKDIR /src
 COPY package*.json ./
 RUN npm install
 
-EXPOSE 3000
-
 # copy all the files in local directory to container working directory
 COPY . .
+
+# If fail tests, stops the build
+RUN echo "Running tests..."
+RUN npm run test:ci -- --verbose || (echo "Tests failed" && exit 1)
+
+# If tests pass, continue with the build
+FROM base AS runtime
+
+EXPOSE 3000
 
 CMD ["npm", "run", "dev"]
